"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { jsPDF } from "jspdf";
import { useToast } from "@/components/Toast";
import type { ClauseItem, ContractAnalysis } from "@/types/analysis";
import { isContractAnalysis } from "@/types/analysis";

const LEXSCAN_ANALYSIS_KEY = "lexscan-analysis";

const CONTRACT_TYPES = [
  "NDA",
  "Service Agreement",
  "Employment Contract",
  "Vendor Agreement",
  "SaaS Agreement",
] as const;

type NegotiateFormData = {
  name: string;
  company: string;
  email: string;
  recipientName: string;
  recipientCompany: string;
  contractRef: string;
  contractType: string;
};

type NegotiationLetter = {
  subject: string;
  opening: string;
  clauses: { number: number; title: string; body: string }[];
  closing: string;
  valediction: string;
};

const emptyForm: NegotiateFormData = {
  name: "",
  company: "",
  email: "",
  recipientName: "",
  recipientCompany: "",
  contractRef: "",
  contractType: "NDA",
};

function formatLetterDate(d: Date): string {
  return d.toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function clauseBorderClass(risk: string): string {
  if (risk === "high") return "border-l-4 border-risk-high";
  if (risk === "medium") return "border-l-4 border-risk-medium";
  return "border-l-4 border-risk-low";
}

function riskBadgeClass(risk: string): string {
  if (risk === "high")
    return "bg-risk-high/10 text-risk-high ring-1 ring-risk-high/20";
  if (risk === "medium")
    return "bg-risk-medium/10 text-risk-medium ring-1 ring-risk-medium/25";
  return "bg-risk-low/10 text-risk-low ring-1 ring-risk-low/25";
}

function buildPlainLetter(
  letter: NegotiationLetter,
  form: NegotiateFormData,
  dateStr: string
): string {
  const lines: string[] = [
    "WITHOUT PREJUDICE",
    "",
    form.name,
    form.company,
    form.email,
    "",
    dateStr,
    "",
    `Contract reference: ${form.contractRef}`,
    "",
    form.recipientName,
    form.recipientCompany,
    "",
    `Re: ${letter.subject}`,
    "",
    `Dear ${form.recipientName},`,
    "",
    letter.opening,
    "",
  ];
  for (const c of letter.clauses) {
    lines.push(`${c.number}. ${c.title}`);
    lines.push(c.body);
    lines.push("");
  }
  lines.push(letter.closing, "", letter.valediction + ",", "", "________________________", "", form.name, form.company);
  return lines.join("\n");
}

async function buildNegotiationPdf(
  letter: NegotiationLetter,
  form: NegotiateFormData,
  dateStr: string
): Promise<jsPDF> {
  const { jsPDF } = await import("jspdf");
  const margin = 25;
  const pageH = 297;
  const pageW = 210;
  const contentW = pageW - margin * 2;
  const footerReserve = 16;
  const bottomSafe = pageH - margin - footerReserve;

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = margin;

  const ensureSpace = (neededMm: number) => {
    if (y + neededMm > bottomSafe) {
      doc.addPage();
      y = margin;
    }
  };

  const printLines = (
    text: string,
    fontSize: number,
    lineMm: number,
    style: "normal" | "bold" = "normal"
  ) => {
    doc.setFont("times", style);
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, contentW) as string[];
    for (const line of lines) {
      ensureSpace(lineMm);
      doc.text(line, margin, y);
      y += lineMm;
    }
    doc.setFont("times", "normal");
  };

  const addFooter = (pageIndex: number, totalPages: number) => {
    doc.setFontSize(9);
    doc.setFont("times", "normal");
    doc.text(
      "This letter is generated by Clarifai and does not constitute legal advice.",
      pageW / 2,
      pageH - 12,
      { align: "center" }
    );
    doc.text(`${pageIndex} / ${totalPages}`, pageW / 2, pageH - 6, {
      align: "center",
    });
  };

  const flushFooters = () => {
    const total = doc.getNumberOfPages();
    for (let i = 1; i <= total; i++) {
      doc.setPage(i);
      addFooter(i, total);
    }
  };

  doc.setFont("times", "normal");
  doc.setFontSize(9);
  doc.text("WITHOUT PREJUDICE", pageW / 2, y, { align: "center" });
  y += 10;

  const blockTop = y;
  doc.setFontSize(10);
  doc.text(form.name, margin, blockTop);
  doc.text(form.company, margin, blockTop + 5);
  doc.text(form.email, margin, blockTop + 10);
  doc.text(dateStr, pageW - margin, blockTop, { align: "right" });
  y = blockTop + 16;

  printLines(`Contract reference: ${form.contractRef}`, 10, 5);
  y += 2;

  printLines(form.recipientName, 10, 5);
  printLines(form.recipientCompany, 10, 5);
  y += 2;

  printLines(`Re: ${letter.subject}`, 10, 5);
  y += 2;

  printLines(`Dear ${form.recipientName},`, 10, 5);
  y += 2;

  printLines(letter.opening, 10, 5);
  y += 2;

  for (const c of letter.clauses) {
    ensureSpace(14);
    printLines(`${c.number}. ${c.title}`, 11, 5.5, "bold");
    printLines(c.body, 10, 5);
    y += 2;
  }

  printLines(letter.closing, 10, 5);
  y += 2;
  printLines(`${letter.valediction},`, 10, 5);
  y += 4;

  ensureSpace(10);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  printLines(form.name, 10, 5);
  printLines(form.company, 10, 5);

  flushFooters();
  return doc;
}

export default function NegotiatePage() {
  const { showToast } = useToast();
  const [hydrated, setHydrated] = useState(false);
  const [analysis, setAnalysis] = useState<ContractAnalysis | null>(null);
  const [form, setForm] = useState<NegotiateFormData>(emptyForm);
  const [clauseChecked, setClauseChecked] = useState<boolean[]>([]);
  const [letter, setLetter] = useState<NegotiationLetter | null>(null);
  const [generating, setGenerating] = useState(false);

  const letterDate = useMemo(() => formatLetterDate(new Date()), []);

  useEffect(() => {
    const raw = sessionStorage.getItem(LEXSCAN_ANALYSIS_KEY);
    if (raw) {
      try {
        const parsed: unknown = JSON.parse(raw);
        if (isContractAnalysis(parsed)) {
          setAnalysis(parsed);
          setClauseChecked(
            parsed.clauses.map((c) => c.riskLevel === "high")
          );
        }
      } catch {
        /* ignore */
      }
    }
    setHydrated(true);
  }, []);

  const toggleClause = useCallback((index: number) => {
    setClauseChecked((prev) => {
      const next = [...prev];
      next[index] = !next[index];
      return next;
    });
  }, []);

  const formValid = useMemo(() => {
    return (
      form.name.trim() &&
      form.company.trim() &&
      form.email.trim() &&
      form.recipientName.trim() &&
      form.recipientCompany.trim() &&
      form.contractRef.trim() &&
      form.contractType
    );
  }, [form]);

  const generateLetter = async () => {
    if (!analysis) return;
    if (!formValid) {
      showToast("Please complete all form fields.", "error");
      return;
    }
    const selected = analysis.clauses.filter((_, i) => clauseChecked[i]);
    if (selected.length === 0) {
      showToast("Select at least one clause for the letter.", "error");
      return;
    }

    setGenerating(true);
    setLetter(null);
    try {
      const res = await fetch("/api/negotiate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          formData: form,
          selectedClauses: selected,
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) {
        throw new Error((data as { error?: string }).error || "Generation failed");
      }
      setLetter(data as NegotiationLetter);
      showToast("Negotiation letter generated.", "success");
    } catch (e) {
      showToast(
        e instanceof Error ? e.message : "Could not generate letter.",
        "error"
      );
    } finally {
      setGenerating(false);
    }
  };

  const copyLetter = async () => {
    if (!letter) return;
    const text = buildPlainLetter(letter, form, letterDate);
    try {
      await navigator.clipboard.writeText(text);
      showToast("Letter copied to clipboard.", "success");
    } catch {
      showToast("Could not copy to clipboard.", "error");
    }
  };

  const downloadPdf = async () => {
    if (!letter) return;
    const safeRef = form.contractRef.replace(/[^a-zA-Z0-9-_]/g, "_");
    const doc = await buildNegotiationPdf(letter, form, letterDate);
    doc.save(`negotiation_letter_${safeRef}.pdf`);
    showToast("PDF downloaded.", "success");
  };

  if (!hydrated) {
    return (
      <div className="min-h-screen bg-slate-50 px-4 py-16 text-navy sm:px-6">
        <div className="mx-auto max-w-3xl animate-pulse rounded-card border border-line bg-white p-8 shadow-card">
          <div className="h-6 w-48 rounded bg-slate-200" />
        </div>
      </div>
    );
  }

  if (!analysis) {
    return (
      <div className="min-h-screen bg-slate-50 px-4 py-16 text-navy sm:px-6">
        <div className="mx-auto max-w-lg rounded-card border border-line bg-white p-8 text-center shadow-card">
          <p className="text-lg font-semibold">No analysis found — go to Analyze first</p>
          <p className="mt-2 text-sm text-slate-600">
            Run a contract scan, then open the negotiation letter from your results.
          </p>
          <Link
            href="/analyze"
            className="mt-6 inline-flex rounded-lg bg-accent px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-accent/90"
          >
            Go to Analyze
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 text-navy">
      <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:py-14">
        <p className="text-xs font-bold uppercase tracking-wide text-accent">
          Clarifai workspace
        </p>
        <h1 className="mt-2 text-3xl font-semibold tracking-tight">
          Generate negotiation letter
        </h1>
        <p className="mt-2 max-w-2xl text-sm text-slate-600 sm:text-base">
          Without prejudice — draft a formal letter referencing flagged clauses from your
          last analysis.
        </p>

        {/* Step 1 */}
        <section className="mt-10 rounded-card border border-line bg-white p-6 shadow-card sm:p-8">
          <h2 className="text-lg font-semibold text-navy">Step 1 — Your details</h2>
          <div className="mt-6 grid gap-4 sm:grid-cols-2">
            <label className="block text-sm font-medium text-slate-700">
              Your full name
              <input
                className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm shadow-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
                value={form.name}
                onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
              />
            </label>
            <label className="block text-sm font-medium text-slate-700">
              Your company / designation
              <input
                className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm shadow-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
                value={form.company}
                onChange={(e) => setForm((f) => ({ ...f, company: e.target.value }))}
              />
            </label>
            <label className="block text-sm font-medium text-slate-700 sm:col-span-2">
              Your email
              <input
                type="email"
                className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm shadow-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
                value={form.email}
                onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))}
              />
            </label>
            <label className="block text-sm font-medium text-slate-700">
              Recipient name
              <input
                className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm shadow-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
                value={form.recipientName}
                onChange={(e) =>
                  setForm((f) => ({ ...f, recipientName: e.target.value }))
                }
              />
            </label>
            <label className="block text-sm font-medium text-slate-700">
              Recipient company
              <input
                className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm shadow-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
                value={form.recipientCompany}
                onChange={(e) =>
                  setForm((f) => ({ ...f, recipientCompany: e.target.value }))
                }
              />
            </label>
            <label className="block text-sm font-medium text-slate-700">
              Contract reference number
              <input
                placeholder="e.g. NDA-2025-001"
                className="mt-1 w-full rounded-lg border border-line px-3 py-2 text-sm shadow-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
                value={form.contractRef}
                onChange={(e) =>
                  setForm((f) => ({ ...f, contractRef: e.target.value }))
                }
              />
            </label>
            <label className="block text-sm font-medium text-slate-700">
              Contract type
              <select
                className="mt-1 w-full rounded-lg border border-line bg-white px-3 py-2 text-sm shadow-sm focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
                value={form.contractType}
                onChange={(e) =>
                  setForm((f) => ({ ...f, contractType: e.target.value }))
                }
              >
                {CONTRACT_TYPES.map((t) => (
                  <option key={t} value={t}>
                    {t}
                  </option>
                ))}
              </select>
            </label>
          </div>
        </section>

        {/* Step 2 */}
        <section className="mt-8 rounded-card border border-line bg-white p-6 shadow-card sm:p-8">
          <h2 className="text-lg font-semibold text-navy">Step 2 — Clauses to include</h2>
          <p className="mt-1 text-sm text-slate-600">
            High-risk clauses are selected by default. Adjust before generating.
          </p>
          <div className="mt-6 space-y-4">
            {analysis.clauses.map((c: ClauseItem, idx: number) => (
              <label
                key={idx}
                className={`flex cursor-pointer gap-4 rounded-card border border-line bg-slate-50/80 p-4 shadow-sm transition hover:bg-white ${clauseBorderClass(c.riskLevel)}`}
              >
                <input
                  type="checkbox"
                  className="mt-1 h-4 w-4 shrink-0 rounded border-line text-accent focus:ring-accent"
                  checked={clauseChecked[idx] ?? false}
                  onChange={() => toggleClause(idx)}
                />
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="font-semibold text-navy">{c.name}</span>
                    <span
                      className={`rounded-badge px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide ${riskBadgeClass(c.riskLevel)}`}
                    >
                      {c.riskLevel} risk
                    </span>
                  </div>
                  <p className="mt-2 text-sm leading-relaxed text-slate-700">
                    {c.explanation}
                  </p>
                </div>
              </label>
            ))}
          </div>
        </section>

        {/* Step 3 */}
        <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-xs text-slate-500">
            Filename preview:{" "}
            <span className="font-mono text-slate-700">
              negotiation_letter_{form.contractRef.replace(/[^a-zA-Z0-9-_]/g, "_") || "ref"}
              .pdf
            </span>
          </p>
          <button
            type="button"
            onClick={generateLetter}
            disabled={generating || !formValid}
            className="inline-flex items-center justify-center rounded-lg bg-accent px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-accent/90 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {generating ? "Generating…" : "Generate official negotiation letter"}
          </button>
        </div>

        {/* Step 4 */}
        {letter && (
          <div className="mt-10 space-y-4">
            <div className="flex flex-col gap-3 rounded-card border border-line bg-white p-4 shadow-card sm:flex-row sm:flex-wrap sm:items-center sm:justify-between sm:p-5">
              <div className="text-sm text-slate-600">
                <span className="font-medium text-navy">File: </span>
                <span className="font-mono text-xs">
                  negotiation_letter_
                  {form.contractRef.replace(/[^a-zA-Z0-9-_]/g, "_") || "ref"}.pdf
                </span>
              </div>
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={copyLetter}
                  className="rounded-lg border border-line bg-white px-4 py-2 text-sm font-semibold text-navy shadow-sm transition hover:border-accent/40"
                >
                  Copy letter
                </button>
                <button
                  type="button"
                  onClick={downloadPdf}
                  className="rounded-lg border border-line bg-slate-900 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-slate-800"
                >
                  Download PDF
                </button>
              </div>
            </div>

            <article className="rounded-card border border-line bg-white p-8 shadow-card sm:p-10">
              <div className="font-serif text-navy" style={{ fontFamily: "Georgia, serif" }}>
                <p className="text-center text-[11px] font-semibold uppercase tracking-[0.2em] text-slate-600">
                  Without prejudice
                </p>

                <div className="mt-8 flex justify-between gap-6 text-sm leading-relaxed">
                  <div>
                    <p className="font-semibold">{form.name}</p>
                    <p>{form.company}</p>
                    <p className="text-slate-600">{form.email}</p>
                  </div>
                  <div className="text-right text-slate-700">{letterDate}</div>
                </div>

                <p className="mt-8 text-sm">
                  <span className="font-semibold">Contract reference:</span>{" "}
                  {form.contractRef}
                </p>

                <div className="mt-6 text-sm leading-relaxed">
                  <p className="font-semibold">{form.recipientName}</p>
                  <p>{form.recipientCompany}</p>
                </div>

                <p className="mt-6 text-sm">
                  <span className="font-semibold">Re:</span> {letter.subject}
                </p>

                <p className="mt-6 text-sm leading-relaxed">
                  Dear {form.recipientName},
                </p>

                <p className="mt-4 text-[10pt] leading-relaxed text-slate-800">
                  {letter.opening}
                </p>

                <div className="mt-6 space-y-5">
                  {letter.clauses.map((c) => (
                    <section key={c.number} className="text-[10pt] leading-relaxed">
                      <h3 className="text-[11pt] font-semibold text-navy">
                        {c.number}. {c.title}
                      </h3>
                      <p className="mt-2 text-slate-800">{c.body}</p>
                    </section>
                  ))}
                </div>

                <p className="mt-6 text-[10pt] leading-relaxed text-slate-800">
                  {letter.closing}
                </p>

                <p className="mt-6 text-sm">{letter.valediction},</p>

                <hr className="mt-8 border-line" />

                <p className="mt-6 text-sm font-semibold">{form.name}</p>
                <p className="text-sm text-slate-700">{form.company}</p>
              </div>

              <p className="mt-10 text-center text-[9px] text-slate-500">
                This letter is generated by Clarifai and does not constitute legal advice.
              </p>
            </article>
          </div>
        )}
      </div>
    </div>
  );
}
