"use client";

type NegotiateFormData = {
  name: string;
  company: string;
  email: string;
  recipientName: string;
  recipientCompany: string;
  contractRef: string;
  contractType: string;
};

type NegotiationLetter = {
  subject: string;
  opening: string;
  clauses: { number: number; title: string; body: string }[];
  closing: string;
  valediction: string;
};

export async function buildNegotiationPdf(
  letter: NegotiationLetter,
  form: NegotiateFormData,
  dateStr: string
) {
  if (typeof window === "undefined") return;

  const { jsPDF } = await import("jspdf");
  const margin = 25;
  const pageH = 297;
  const pageW = 210;
  const contentW = pageW - margin * 2;
  const footerReserve = 16;
  const bottomSafe = pageH - margin - footerReserve;

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = margin;

  const ensureSpace = (neededMm: number) => {
    if (y + neededMm > bottomSafe) {
      doc.addPage();
      y = margin;
    }
  };

  const printLines = (
    text: string,
    fontSize: number,
    lineMm: number,
    style: "normal" | "bold" = "normal"
  ) => {
    doc.setFont("times", style);
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, contentW) as string[];
    for (const line of lines) {
      ensureSpace(lineMm);
      doc.text(line, margin, y);
      y += lineMm;
    }
    doc.setFont("times", "normal");
  };

  const addFooter = (pageIndex: number, totalPages: number) => {
    doc.setFontSize(9);
    doc.setFont("times", "normal");
    doc.text(
      "This letter is generated by Clarifai and does not constitute legal advice.",
      pageW / 2,
      pageH - 12,
      { align: "center" }
    );
    doc.text(`${pageIndex} / ${totalPages}`, pageW / 2, pageH - 6, {
      align: "center",
    });
  };

  const flushFooters = () => {
    const total = doc.getNumberOfPages();
    for (let i = 1; i <= total; i++) {
      doc.setPage(i);
      addFooter(i, total);
    }
  };

  doc.setFont("times", "normal");
  doc.setFontSize(9);
  doc.text("WITHOUT PREJUDICE", pageW / 2, y, { align: "center" });
  y += 10;

  const blockTop = y;
  doc.setFontSize(10);
  doc.text(form.name, margin, blockTop);
  doc.text(form.company, margin, blockTop + 5);
  doc.text(form.email, margin, blockTop + 10);
  doc.text(dateStr, pageW - margin, blockTop, { align: "right" });
  y = blockTop + 16;

  printLines(`Contract reference: ${form.contractRef}`, 10, 5);
  y += 2;

  printLines(form.recipientName, 10, 5);
  printLines(form.recipientCompany, 10, 5);
  y += 2;

  printLines(`Re: ${letter.subject}`, 10, 5);
  y += 2;

  printLines(`Dear ${form.recipientName},`, 10, 5);
  y += 2;

  printLines(letter.opening, 10, 5);
  y += 2;

  for (const c of letter.clauses) {
    ensureSpace(14);
    printLines(`${c.number}. ${c.title}`, 11, 5.5, "bold");
    printLines(c.body, 10, 5);
    y += 2;
  }

  printLines(letter.closing, 10, 5);
  y += 2;
  printLines(`${letter.valediction},`, 10, 5);
  y += 4;

  ensureSpace(10);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  printLines(form.name, 10, 5);
  printLines(form.company, 10, 5);

  flushFooters();
  return doc;
}
