"use client";

type NegotiateFormData = {
  name: string;
  company: string;
  email: string;
  recipientName: string;
  recipientCompany: string;
  contractRef: string;
  contractType: string;
};

type NegotiationLetter = {
  subject: string;
  opening: string;
  clauses: { number: number; title: string; body: string }[];
  closing: string;
  valediction: string;
};

export async function buildNegotiationPdf(
  letter: NegotiationLetter,
  form: NegotiateFormData,
  dateStr: string
) {
  if (typeof window === "undefined") return;

  const { jsPDF } = await import("jspdf");
  const margin = 25;
  const pageH = 297;
  const pageW = 210;
  const contentW = pageW - margin * 2;
  const footerReserve = 16;
  const bottomSafe = pageH - margin - footerReserve;

  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = margin;

  const ensureSpace = (neededMm: number) => {
    if (y + neededMm > bottomSafe) {
      doc.addPage();
      y = margin;
    }
  };

  const printLines = (
    text: string,
    fontSize: number,
    lineMm: number,
    style: "normal" | "bold" = "normal"
  ) => {
    doc.setFont("times", style);
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, contentW) as string[];
    for (const line of lines) {
      ensureSpace(lineMm);
      doc.text(line, margin, y);
      y += lineMm;
    }
    doc.setFont("times", "normal");
  };

  const addFooter = (pageIndex: number, totalPages: number) => {
    doc.setFontSize(9);
    doc.setFont("times", "normal");
    doc.text(
      "This letter is generated by Clarifai and does not constitute legal advice.",
      pageW / 2,
      pageH - 12,
      { align: "center" }
    );
    doc.text(`${pageIndex} / ${totalPages}`, pageW / 2, pageH - 6, {
      align: "center",
    });
  };

  const flushFooters = () => {
    const total = doc.getNumberOfPages();
    for (let i = 1; i <= total; i++) {
      doc.setPage(i);
      addFooter(i, total);
    }
  };

  const cx = pageW / 2;
  const logoY = 18;
  const size = 10;

  // Outer diamond
  doc.setDrawColor(201, 150, 60);
  doc.setLineWidth(0.4);
  doc.lines(
    [
      [size, size],
      [size, -size],
      [-size, -size],
      [-size, size],
    ],
    cx,
    logoY + size,
    [1, 1],
    null,
    true
  );

  // Inner diamond (smaller)
  const s2 = size - 2;
  doc.setLineWidth(0.2);
  doc.lines(
    [
      [s2, s2],
      [s2, -s2],
      [-s2, -s2],
      [-s2, s2],
    ],
    cx,
    logoY + size,
    [1, 1],
    null,
    true
  );

  // C monogram
  doc.setFont("times", "bold");
  doc.setFontSize(11);
  doc.setTextColor(201, 150, 60);
  doc.text("C", cx, logoY + size + 2, { align: "center" });

  // CLARIFAI text below C
  doc.setFont("times", "normal");
  doc.setFontSize(5);
  doc.setTextColor(180, 130, 50);
  doc.setCharSpace(2);
  doc.text("CLARIFAI", cx, logoY + size + 6, { align: "center" });
  doc.setCharSpace(0);

  // Two thin lines
  doc.setDrawColor(201, 150, 60);
  doc.setLineWidth(0.2);
  doc.line(cx - 8, logoY + size + 7.5, cx + 8, logoY + size + 7.5);
  doc.line(cx - 8, logoY + size + 8.5, cx + 8, logoY + size + 8.5);

  // WITHOUT PREJUDICE tiny text
  doc.setFontSize(4);
  doc.setTextColor(180, 130, 50);
  doc.setCharSpace(1);
  doc.text("WITHOUT PREJUDICE", cx, logoY + size + 11, { align: "center" });
  doc.setCharSpace(0);

  // Reset colors for rest of letter
  doc.setTextColor(0, 0, 0);
  doc.setDrawColor(0, 0, 0);

  y = logoY + size * 2 + 20;

  const blockTop = y;
  doc.setFontSize(10);
  doc.text(form.name, margin, blockTop);
  doc.text(form.company, margin, blockTop + 5);
  doc.text(form.email, margin, blockTop + 10);
  doc.text(dateStr, pageW - margin, blockTop, { align: "right" });
  y = blockTop + 16;

  printLines(`Contract reference: ${form.contractRef}`, 10, 5);
  y += 2;

  printLines(form.recipientName, 10, 5);
  printLines(form.recipientCompany, 10, 5);
  y += 2;

  printLines(`Re: ${letter.subject}`, 10, 5);
  y += 2;

  printLines(`Dear ${form.recipientName},`, 10, 5);
  y += 2;

  printLines(letter.opening, 10, 5);
  y += 2;

  for (const c of letter.clauses) {
    ensureSpace(14);
    printLines(`${c.number}. ${c.title}`, 11, 5.5, "bold");
    printLines(c.body, 10, 5);
    y += 2;
  }

  printLines(letter.closing, 10, 5);
  y += 2;
  printLines(`${letter.valediction},`, 10, 5);
  y += 4;

  ensureSpace(10);
  doc.setLineWidth(0.3);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  printLines(form.name, 10, 5);
  printLines(form.company, 10, 5);

  flushFooters();
  return doc;
}
